### ISSUE TITLE
Email Tools

### ISSUE THREAD

**Issue by rmrhz** [ilya-dev/belt#6]
Any considerations of adding email tools?

**Comment by ilya-dev** [comment]
What do you mean by "email tools"?

**Comment by rmrhz** [comment]
Like email validation, obfuscation, and such.

**Comment by ilya-dev** [comment]
Hm...will look into that.

**Comment by rmrhz** [comment]
I can do a pull request then edit some docs tomorrow if that'll be okay.

**Comment by ilya-dev** [comment]
That'd be fine.
